services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.13-alpine3.23"
    env_file:
      - ../.env.development
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - "5432:5432"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
